export const PROGRAM_BEM = [
  {
    title: "Web Development Bootcamp",
    desc: "Pelajari dasar hingga lanjutan pengembangan web menggunakan HTML, CSS, JavaScript, dan framework modern.",
    href: "/program/web-development",
    image: "/images/programs/web-dev.png",
    tags: ["Web", "Frontend", "Backend", "Beginner"],
  },
  {
    title: "Mobile App Development",
    desc: "Bangun aplikasi mobile cross-platform dengan React Native dan Flutter dari nol.",
    href: "/program/mobile-app",
    image: "/images/programs/mobile-app.png",
    tags: ["Mobile", "React Native", "Flutter"],
  },
  {
    title: "UI/UX Design Fundamentals",
    desc: "Pahami prinsip desain, user research, wireframing, dan prototyping berbasis user-centered design.",
    href: "/program/ui-ux",
    image: "/images/programs/ui-ux.png",
    tags: ["UI/UX", "Design", "Beginner"],
  },
  {
    title: "Backend Engineering",
    desc: "Fokus pada arsitektur backend, REST API, database, autentikasi, dan scalability.",
    href: "/program/backend",
    image: "/images/programs/backend.png",
    tags: ["Backend", "API", "Database"],
  },
  {
    title: "Data Science & Analytics",
    desc: "Analisis data, visualisasi, dan machine learning menggunakan Python dan tools data modern.",
    href: "/program/data-science",
    image: "/images/programs/data-science.png",
    tags: ["Data", "Python", "Analytics"],
  },
  {
    title: "Cyber Security Essentials",
    desc: "Pelajari dasar keamanan sistem, network security, dan vulnerability assessment.",
    href: "/program/cyber-security",
    image: "/images/programs/cyber-security.png",
    tags: ["Security", "Networking", "Fundamental"],
  },
  {
    title: "Cloud Computing",
    desc: "Deploy dan kelola aplikasi di cloud menggunakan AWS, Docker, dan Kubernetes.",
    href: "/program/cloud-computing",
    image: "/images/programs/cloud.png",
    tags: ["Cloud", "AWS", "DevOps"],
  },
  {
    title: "Game Development",
    desc: "Kembangkan game 2D dan 3D menggunakan Unity dan fundamental game engine.",
    href: "/program/game-development",
    image: "/images/programs/game-dev.png",
    tags: ["Game", "Unity", "3D"],
  },
  {
    title: "AI & Machine Learning",
    desc: "Bangun model AI, NLP, dan computer vision dengan pendekatan praktis.",
    href: "/program/ai-ml",
    image: "/images/programs/ai-ml.png",
    tags: ["AI", "Machine Learning", "Advanced"],
  },
  {
    title: "DevOps Engineering",
    desc: "Automasi CI/CD, monitoring, dan infrastructure as code untuk workflow modern.",
    href: "/program/devops",
    image: "/images/programs/devops.png",
    tags: ["DevOps", "CI/CD", "Infrastructure"],
  },
];
